server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_cafe_db?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root
    password: rt123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin123
